Merge from 4.3.0 (#146)
* Version 4.2.0.Final

* Exclude deprecated artifact

* Use scim-model instead of deprecated artifact

* Remove temporary build file

* Version 4.2.1.Final

* Upgrade jquery (XSS vulnerability)

* Update user-cert plugin #123

* Misc fixes

* Rename cust page

* Conform to 4.2 changes

* Version 4.2.1.Final

* Workaround to make udpates & removals of fido2 devices work again

* Fix typo

* Make updates of domains safer (prevents clashing when SyncSettingsTimer runs)

* Version 4.2.2-SNAPSHOT

* Ensure unconsumed response is closed

* Better computation of scopes

* Update enrollment API swagger doc

* Better computation of scopes Pt. 2

* Better computation of scopes Pt. 3

* #77 Plugin to enroll and authenticate DUO credentials

* #77

* #77 increasing the height of iframe

* Minor fixes

* Edit and list DUO credential related fixes
#77

* sample file

* Delete duo_creds.json

* sample file

* #125

* Jenkins build

* minor

* sndFactorUtils

* correcting casa-shared version to 4.2.2

* Prevent empty OP host field in OXD form

* #129 (4.2.2)

* Add missing base DN (4.2.2) #129

* Add missing base DN (4.2.2) #129

* Version 4.2.2.Final

* Version 4.2.3-SNAPSHOT

* Delete unnecessary directories

* Avoid usage of UI class in VM

* Remove DelegatingVariableResolver from VMs

* Update ZK version

* Use Notify Change shortcut method

* Update message box header style

* Remove Command annotations

* Avoid usage of UI class in VM, Pt 2

* Avoid usage of UI class in VM, Pt 3

* Shorten expression

* Use shortcut to set VM init class

* Shorten command bindings, Pt 1

* Shorten command bindings, Pt 2

* Add 'onEnter' handler

* Reduce font size of loading indicator

* Version 4.2.3.Final

* Version 4.3.0.Final

* Add missing params

* Add services and apply minor refactoring #127

* Misc services updates #127

* Add REST service for 2FA settings plugin #127

* Add prefix to endpoints and adjust MIME types

* Package refactoring

* Filter adjustments #130

* Add exception processing #130

* Add protection scopes #127

* Add protection scopes (2fa plugin WS) #127

* Scopes handling adjustments #130

* Update CORS endpoint definition

* Update enrollment API swagger doc

* Add swagger client for consumption of config API #127

* Bump junit from 4.12 to 4.13.1 in /config-client

Bumps [junit](https://github.com/junit-team/junit4) from 4.12 to 4.13.1.
- [Release notes](https://github.com/junit-team/junit4/releases)
- [Changelog](https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.12.md)
- [Commits](https://github.com/junit-team/junit4/compare/r4.12...r4.13.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Update enrollment API swagger doc Pt. 2

* Add config-client module to project #127

* Minor update of swagger doc #127

* Code formatting #127

* Update 4.2 refs

* Update version

* Update version

* Add scope param to token request

* Sync wrt master

* Use latest jackson libs

* fix(dependencies): avoid NoClassDefFoundError of JacksonFeature

* chore(dependencies): use latest 3.x resteasy

* feat: add param in 2fa settings plugin to allow preferred method selection #87

* feat: add method to interface to account preferred method #87

* feat: add UI elements and behavior to allow preferred method selection in GUI #87

* refactor: Make UI fragment look similar to latest preferred.zul changes

* refactor: Allow to properly hide link when 2fa is disabled #87

* feat: add note about preferred authn method on mobile platforms #87

* feat(casa): allow preferred method to be prompted https://github.com/GluuFederation/casa/issues/87

* feat: add preferred method parameter to 2fa api #87

* feat: use new ORM libs

* feat: use new ORM libs

* feat: use new ORM libs

* feat: use new ORM libs

* feat: use new ORM libs

* feat: add new ORM libs

* fix: update gitignore

* fix: script denies authentication when used as first alternative

* chore: Minor typos

* chore: remove unnecessary dep

* chore: remove unused method

* fix: prepend plus sign #138

* chore: conform class to update in TwilioMobilePhoneService

* chore: update twilio lib

* feat: #139

* feat: #139 (admin UI update)

* feat: #139 (minor style enhancements)

* feat: #139 (adjust admin API to conform)

* chore: update config api client

* chore: remove unnecessary styles

* fix: styles updates

* chore: reduce log noise

* fix: prevent unexpected filter generated in stig jvm

* fix: avoid NPE if user has no trusted devices

* feat: include Touch ID as a fido2 device #140

* fix: webauthn - NotAllowedError is thrown randomly if the user gesture invokes a setTimeout or callback

* docs: use version 8 for javadoc generation

* docs: use version 8 for javadoc generation

* chore: main descriptor maintenance

* chore: replace findbugs plugin

* chore: replace findbugs plugin pt. 2

* chore: refactor class

* chore: update dependency

* chore: refactor class

* feat: Casa plugin for Stytch SMS OTP credentials #142

* Version 4.3.0.Final

* fix: sort scopes list

* fix: sort scopes list

* fix: Fido2 enrollment cancelling #143

Co-authored-by: Jose <bonustrack310@gmail.com>
Co-authored-by: Madhumita <madhu@gluu.org>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>